package com.innstack.point

import com.innstack.point.User;

rule subBackNumsPoint
    // 发生退货，扣减10分
    salience 10
    lock-on-active true
    when
        $user : User(backNums >= 1)
    then
        $user.setPoint($user.getPoint()-10);
        $user.recordPointLog($user.getUserName(),"subBackNumsPoint");
end

rule subBackMondyPoint
    // 退货金额大于100，扣减100分
    salience 9
    lock-on-active true
    when
        $user : User(backMondy >= 100)
    then
        $user.setPoint($user.getPoint()-10);
        $user.recordPointLog($user.getUserName(),"subBackMondyPoint");
end